language: node_js
node_js:
  - 12.9.1
cache:
  directories:
    - node_modules
before_install:
  - npm install -g hexo-cli
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
install:
  - npm install
script:
  - hexo clean
  - hexo generate
deploy:
  provider: script
  script: aws s3 sync --region ap-northeast-1 --delete public s3://sjmyuan-ganggang

env:
  global:
    - secure: m7Ghq7tRAR+P8nunb61AkggXcuaB+8MsjJZbajfrEtSUMoj6rkjoW9KmT3K9V//opBDNkRZERLsS/rAoHORxjRrDDHuW2nyj63MzV9Pu4GPH5p0xXNmBGZTlgFWHMgsnvYIcVcRGv2FP1PwyNCDVUeYJGDAE7MAcHYMpLb0dKal41shqt8M9G35Jss2gEdnweoPXgX80mioOnReWz2O2wM7TvfEpSxYQXhFdR8ACcZTleP3u0YzTd0wPmC+lSmovHuwDm8qvC75HWb6rYNhMcJbMRDowjRsev6zo+b9+e05jFwmfzH0HMUjO39+cKhvjrVunvNC0zr7doSh3VvZhgweuqKKoDGrP3xn83EdxfDu1vh4Dyg4TphvjKmlN8eXWYevRld+s/s8mobMMqF5Ixv9qJvdyMb48je2JSmUhqs81KX6iS3zDcXwg/ACW2kiQtmVn4iAdmQ1EPdu2a1LIdaQ3d9MBsC8d3LYKxVigF4EfVl81wBwCMqvqLz97wydSU5j6MVZjhctVpVTZO6uFs1XJJrTKq3xcIYzoTXsEQOULOrrnsOcn+FjE7HvAeiKoF1zEjGTS7sCovYUa01sPuhFvmZuPJCUVlCdzo14cEmSmNrZKRyBLSdlDisgSvvbDJ9VLgiPY3BPLROBk3TlDyhQBoJNV/+VBr5v6jc89ekE=
    - secure: N8zwi9HMVIEQ4qWFN3my74S2h1mGwLcnZyf3GdMrNLWOLw5q4zzuQkq2LLiIf0W1kjyFN9jvfyhiqLHubfCt5CWBSIO8l/GecCtB2R06eq6jk5+Cf9dggtLo7GFvSw1Lr9n/aAWBE4CMdXkD8AFbUG1oYO/GIY5ToKv9klDVipJVuMOVKjcI4ZwBFlukEgleMv522UDBaKnp/G97SkvJCcWNQi7cMYin49IT2HYxGIae30R145JuKqGAQFrziPreXXMQ8ffu9yGroprDBh0ZwJbZ7EMS+pmijMBbOhCE6eGle30dp5EC680l7+99ZLqKlMKb0V7rMupb1c0Pa6qOWf7VTLtB/SUFgqCBQSNuXWBARwf7BVT5vs9ksHo1IVj7uz/HY87hBCRRlDtcQUXVF1Ss/BauJ/3PTjjhhbWNxfWtQ21BwP+E4F03iSxAlHuroxnObWbFce/93y+Ow09SLxXZyyzToCn8+X/MuG2MpBCIap5ePcxX/aQvc6SPTIBJJYa5FRACeyI7vBhPS1fQBjwhI74HM8yPFpRx2ogTb10al83KP3G+iGuiFKZjDc6SmRN/zs53IYq87zIlQCt6qCVkuz6ZszSn3OFp6UoqWMucmzXBeNmxUJDpTskCOoFZZkJ256WgfbMXKfou2mHWfKi0s901zLfcUKjpnQbl60w=
