jobs:
  build:
    docker:
      - image: 'nikolaik/python-nodejs:python3.8-nodejs14'
    steps:
      - checkout
      - run: npm install -g hexo-cli
      - run: export PATH=$PATH:$HOME/.local/bin
      - run: npm install
      - aws-s3/copy:
          arguments: --recursive
          aws-access-key-id: AWS_ACCESS_KEY_ID_GANGGANG
          aws-region: ap-northeast-1
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_GANGGANG
          from: 's3://sjmyuan-ganggang-posts'
          to: 'source/_posts'
      - run: hexo clean
      - run: hexo generate
      - aws-s3/sync:
          arguments: '--cache-control max-age=259200 --delete'
          aws-access-key-id: AWS_ACCESS_KEY_ID_GANGGANG
          aws-region: ap-northeast-1
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_GANGGANG
          from: public
          to: 's3://sjmyuan-ganggang'
orbs:
  aws-s3: circleci/aws-s3@2.0.0
version: 2.1
