#!/bin/bash
ACCOUNT=$1
DOCKER_CONTAINER=$2
REGION=$3

REPO="${ACCOUNT}.dkr.ecr.${REGION}.amazonaws.com/${DOCKER_CONTAINER}"
TAG="build-$(date -u "+%Y-%m-%d")"

echo "Building Docker Image..."
docker build -t $DOCKER_CONTAINER .

echo "Authenticating against AWS ECR..."
eval $(aws ecr get-login --no-include-email --region $REGION)

echo "Tagging ${REPO}..."
docker tag $DOCKER_CONTAINER:latest $REPO:$TAG
docker tag $DOCKER_CONTAINER:latest $REPO:latest

echo "Deploying to AWS ECR"
docker push $REPO
